#!/bin/bash
# This script is a library. To use it, just type "source log.sh"
MAX_LINES=5000

# Save the LOGFILE name.
if [ ! -v LOGFILE ]; then LOGFILE=log; else LOGFILE+=".log"; fi

# Add a log register with the format "[Date (YYYY-MM-DD HH:MM:SS) - User - Caller - Level] Log".
function log() {
    if [ ! -v LOGS_DIRECORY ] || [ ! -d $LOGS_DIRECORY ]; then return; fi
    echo "$2": [$(date "+%F %T") - $(whoami) - "$1"] "${@:3}" >> $LOGS_DIRECORY/$LOGFILE
    if (( $(wc -l $LOGS_DIRECORY/$LOGFILE | awk '{ print $1 }') > MAX_LINES )); then truncate; fi
}

info() {
	log $1 "INFO" $2
}

warn() {
	log $1 "WARN" $2
}

error() {
	log $1 "ERROR" $2
}

# Truncate the LOGFILE leaving just the last $MAX_LINES lines.
function truncate() {
    tail $LOGS_DIRECORY/$LOGFILE -n $MAX_LINES > $LOGS_DIRECORY/tmp
    mv $LOGS_DIRECORY/tmp $LOGS_DIRECORY/$LOGFILE
}
