#!/bin/bash
GRUPO=$HOME/Grupo06
DIRCONF=$GRUPO/.dirconf
LOGS_DIRECORY=$DIRCONF
LOGFILE=stop
source ./log

if [ ! -v PID_DAEMON ]; then 
	echo "The daemon is not running."
	warn "main" "Daemon was not running when it was attempted to kill."
	exit
fi

kill $PID_DAEMON
echo "Daemon killed." $PID_DAEMON
info "main" "Daemon with PID $PID_DAEMON killed."