#!/bin/bash
GRUPO=$HOME/Grupo06
DIRCONF=$GRUPO/.dirconf
LOGS_DIRECTORY=$DIRCONF
LOGFILE=stop
source ./log

getDaemonPID() {
	while read LINE; do
    	if [[ -z $LINE ]]; then continue; fi
	
	    FIELD=$(echo "$LINE" | cut -d- -f1)
	
    	# Get Daemon line and get PID.
    	case "$FIELD" in
    	    DaemonPID) PID_DAEMON=$(echo "$LINE" | cut -d- -f2);;
    	esac

	done < "$DIRCONF/installation.conf"
}

removeDaemonPID() {
	head -n -1 "$DIRCONF/installation.conf" > $DIRCONF/installation.conf.tmp
	mv $DIRCONF/installation.conf.tmp $DIRCONF/installation.conf
}

getDaemonPID

if [ ! -v PID_DAEMON ]; then 
	echo "The Daemon is not running."
	warn "main" "Daemon was not running when it was attempted to kill."
	exit
fi

kill $PID_DAEMON
echo "Daemon with PID $PID_DAEMON killed."
info "main" "Daemon with PID $PID_DAEMON killed."
removeDaemonPID
